### ISSUE TITLE
Reproducing Results Problem

### ISSUE THREAD

**Issue by saeedranjbar12** [ternaus/kaggle_dstl_submission#4]
Hi.
Great work and thanks for code.
 I was trying to repeat your results on building class (which look impressive) and I just ran your make preduction building file with the model saved in the cache without making any changes in the code. I evaluated the output csv and noticed that the reported 70%ish performabce drops to roughly 35%.  Have you changed the building prediction file that the results do not match?

Thanks.

**Comment by johnny-salz** [comment]
Honestly, it is hard to remember exact details of what's going on here (it's been almost half a year since I last time thought about this particular challenge), and why results may not match. Do you have exactly the same version of Keras and other packages? Also, I can suggest looking at the output masks, it may reveal what king of errors network make (and maybe give a hint why is it so)
