### ISSUE TITLE
Running code only with RGB images

### ISSUE THREAD

**Issue by degiorgig** [ternaus/kaggle_dstl_submission#8]
Dear all,

I was able to run the code with the Kaggle image set, I would like to perform some predictions on sattelite photos of mine, but they are only in RGB (I don't have any Panachormatic  and others wavelength images), is this possible?

Thanks
G.

**Comment by ternaus** [comment]
RGB in the Kaggle problem was in 11 bit (typically it is 8 bit), and it may happen that data that you are trying to run the inference at comes from a different distribution, and quality of the predictions will be low.

We were not allowed to use external data in that Kaggle problem, but if one does not have such a constraint, the easiest way to go would be to use external data like SpaceNet or extract images from OSM and train on it.

**Comment by degiorgig** [comment]
I was thinking about training the network with orthophotos, kind of higher quality images, but they are only RGB and as you mentioned they are 8bit with a resolution of 17500*12000. The positive think is that they are really geolocalized. 
Is it enough to just change the num_channnel to make a prediction? I'm facing some issues.

**Comment by johnny-salz** [comment]
This is fine. There is no problems with running this solution only on RGB data. While IR channels are very valuable to differentiate greenery because of its special spectral characteristics, it is totally fine to use only high resolution RGB for any task. Basically, if human eye could see it, network will too. 
However, different kind of images will require full retrain or at least fine tuning.

**Comment by leader80** [comment]
I downloaded the dataset from spacenet, do you have any good tip to prepare the training data to be compliant with the code?
